services:
  postgresql:
    image: postgres:14-alpine
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=metrics
      - POSTGRES_USER=userm
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./data:/var/lib/postgresql/data