// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metric struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MType                string   `protobuf:"bytes,2,opt,name=m_type,json=mType,proto3" json:"m_type,omitempty"`
	Delta                int64    `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value                float64  `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{0}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Metric) GetMType() string {
	if m != nil {
		return m.MType
	}
	return ""
}

func (m *Metric) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *Metric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type MetricArray struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetricArray) Reset()         { *m = MetricArray{} }
func (m *MetricArray) String() string { return proto.CompactTextString(m) }
func (*MetricArray) ProtoMessage()    {}
func (*MetricArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{1}
}

func (m *MetricArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricArray.Unmarshal(m, b)
}
func (m *MetricArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricArray.Marshal(b, m, deterministic)
}
func (m *MetricArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricArray.Merge(m, src)
}
func (m *MetricArray) XXX_Size() int {
	return xxx_messageInfo_MetricArray.Size(m)
}
func (m *MetricArray) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricArray.DiscardUnknown(m)
}

var xxx_messageInfo_MetricArray proto.InternalMessageInfo

func (m *MetricArray) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterType((*Metric)(nil), "gen.Metric")
	proto.RegisterType((*MetricArray)(nil), "gen.MetricArray")
}

func init() { proto.RegisterFile("api/proto/api.proto", fileDescriptor_2df576b66d12087a) }

var fileDescriptor_2df576b66d12087a = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x49, 0xeb, 0x76, 0x71, 0x2a, 0x8b, 0xc4, 0x3f, 0x84, 0xf5, 0x52, 0x16, 0x84, 0x9e,
	0x52, 0x58, 0xc5, 0x7b, 0x05, 0x8f, 0x5e, 0x8a, 0x27, 0x3d, 0x48, 0xd6, 0x8c, 0x25, 0xd0, 0x36,
	0x21, 0x9b, 0x15, 0xf2, 0xed, 0xa5, 0x19, 0x0a, 0x7b, 0x9b, 0xdf, 0x7b, 0x8f, 0x07, 0x6f, 0xe0,
	0x46, 0x39, 0xd3, 0x38, 0x6f, 0x83, 0x6d, 0x94, 0x33, 0x32, 0x5d, 0x3c, 0xef, 0x71, 0xda, 0x3e,
	0xf4, 0xd6, 0xf6, 0x03, 0x92, 0x79, 0x38, 0xfd, 0x36, 0x38, 0xba, 0x10, 0x29, 0xb1, 0xfb, 0x82,
	0xe2, 0x1d, 0x83, 0x37, 0x3f, 0x7c, 0x03, 0x99, 0xd1, 0x82, 0x55, 0xac, 0xbe, 0xec, 0x32, 0xa3,
	0xf9, 0x1d, 0x14, 0xe3, 0x77, 0x88, 0x0e, 0x45, 0x96, 0xb4, 0xd5, 0xf8, 0x11, 0x1d, 0xf2, 0x5b,
	0x58, 0x69, 0x1c, 0x82, 0x12, 0x79, 0xc5, 0xea, 0xbc, 0x23, 0x98, 0xd5, 0x3f, 0x35, 0x9c, 0x50,
	0x5c, 0x54, 0xac, 0x66, 0x1d, 0xc1, 0xee, 0x19, 0x4a, 0x2a, 0x6f, 0xbd, 0x57, 0x91, 0x3f, 0xc2,
	0x7a, 0x4c, 0x78, 0x14, 0xac, 0xca, 0xeb, 0x72, 0x5f, 0xca, 0x1e, 0x27, 0x49, 0x91, 0x6e, 0xf1,
	0xf6, 0x2d, 0xac, 0x49, 0x3a, 0xf2, 0x17, 0x80, 0x56, 0xeb, 0x85, 0xae, 0xcf, 0xe2, 0xa9, 0x71,
	0x7b, 0x2f, 0x69, 0x9b, 0x5c, 0xb6, 0xc9, 0xb7, 0x79, 0xdb, 0xeb, 0xe6, 0xf3, 0xca, 0x4c, 0x01,
	0xfd, 0xa4, 0x86, 0xf9, 0x1b, 0x87, 0x22, 0xf9, 0x4f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39,
	0x6a, 0x51, 0x28, 0x25, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricsClient interface {
	AddMetrics(ctx context.Context, in *MetricArray, opts ...grpc.CallOption) (*empty.Empty, error)
}

type metricsClient struct {
	cc *grpc.ClientConn
}

func NewMetricsClient(cc *grpc.ClientConn) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) AddMetrics(ctx context.Context, in *MetricArray, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gen.Metrics/AddMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
type MetricsServer interface {
	AddMetrics(context.Context, *MetricArray) (*empty.Empty, error)
}

// UnimplementedMetricsServer can be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (*UnimplementedMetricsServer) AddMetrics(ctx context.Context, req *MetricArray) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMetrics not implemented")
}

func RegisterMetricsServer(s *grpc.Server, srv MetricsServer) {
	s.RegisterService(&_Metrics_serviceDesc, srv)
}

func _Metrics_AddMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).AddMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gen.Metrics/AddMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).AddMetrics(ctx, req.(*MetricArray))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gen.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMetrics",
			Handler:    _Metrics_AddMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/api.proto",
}
